
import java.sql.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author HP
 */
public class GpaCalculator extends javax.swing.JFrame {

    private String query;
    int GPA;

    /**
     * Creates new form GpaCalculator
     */
    public GpaCalculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jform = new javax.swing.JPanel();
        javax.swing.JLabel tfgpa = new javax.swing.JLabel();
        jselect = new javax.swing.JComboBox<>();
        javax.swing.JLabel jfill = new javax.swing.JLabel();
        jcalculate = new javax.swing.JButton();
        jstudents = new javax.swing.JLabel();
        jid = new javax.swing.JLabel();
        jcourses = new javax.swing.JLabel();
        jhours = new javax.swing.JLabel();
        jgrades = new javax.swing.JLabel();
        tfid = new javax.swing.JScrollPane();
        jId = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        tfstudents = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        tfcourses = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        tfhours = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        tfgrades = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tfgpa.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        tfgpa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tfgpa.setText("GPA Calculator");

        jselect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select ", "File", "Database", " " }));

        jfill.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jfill.setText("Please Fill the table with your details");

        jcalculate.setForeground(new java.awt.Color(204, 0, 51));
        jcalculate.setText("Calculate GPA");
        jcalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcalculateActionPerformed(evt);
            }
        });

        jstudents.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jstudents.setForeground(new java.awt.Color(0, 153, 255));
        jstudents.setText("Students Name:");

        jid.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jid.setForeground(new java.awt.Color(0, 153, 255));
        jid.setText("ID:");

        jcourses.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jcourses.setForeground(new java.awt.Color(0, 153, 255));
        jcourses.setText("Courses:");

        jhours.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jhours.setForeground(new java.awt.Color(0, 153, 255));
        jhours.setText("Credit Hours:");

        jgrades.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jgrades.setForeground(new java.awt.Color(0, 153, 255));
        jgrades.setText("Grades:");

        jId.setColumns(20);
        jId.setRows(5);
        tfid.setViewportView(jId);

        tfstudents.setColumns(20);
        tfstudents.setRows(5);
        jScrollPane2.setViewportView(tfstudents);

        tfcourses.setColumns(20);
        tfcourses.setRows(5);
        jScrollPane3.setViewportView(tfcourses);

        tfhours.setColumns(20);
        tfhours.setRows(5);
        jScrollPane4.setViewportView(tfhours);

        tfgrades.setColumns(20);
        tfgrades.setRows(5);
        jScrollPane5.setViewportView(tfgrades);

        javax.swing.GroupLayout jformLayout = new javax.swing.GroupLayout(jform);
        jform.setLayout(jformLayout);
        jformLayout.setHorizontalGroup(
            jformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jformLayout.createSequentialGroup()
                .addGroup(jformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jformLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(jformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jid)
                            .addComponent(jstudents)
                            .addComponent(jcourses)
                            .addComponent(jhours)
                            .addComponent(jgrades))
                        .addGap(27, 27, 27)
                        .addGroup(jformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfid)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
                            .addComponent(jScrollPane3)
                            .addComponent(jScrollPane4)
                            .addComponent(jScrollPane5)))
                    .addGroup(jformLayout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jselect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(297, 297, 297)
                        .addComponent(jcalculate))
                    .addGroup(jformLayout.createSequentialGroup()
                        .addGap(253, 253, 253)
                        .addComponent(jfill))
                    .addGroup(jformLayout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(tfgpa, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(246, Short.MAX_VALUE))
        );
        jformLayout.setVerticalGroup(
            jformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jformLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(tfgpa, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jfill)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jformLayout.createSequentialGroup()
                        .addComponent(jstudents)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jid))
                    .addGroup(jformLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(12, 12, 12)
                        .addComponent(tfid, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcourses)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jhours)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jgrades))
                .addGap(58, 58, 58)
                .addGroup(jformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jselect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcalculate))
                .addGap(266, 266, 266))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jform, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(337, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 16, Short.MAX_VALUE)
                .addComponent(jform, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcalculateActionPerformed
        Dbconnection dbConnection = new Dbconnection();
        Connection conn = dbConnection.getDatabase();

        String jstudents = tfstudents.getText();
        String jid = jId.getText();
        String jcourses = tfcourses.getText();
        String jhours = tfhours.getText();
        String jgrades = tfgrades.getText();
        boolean result = true;

        System.out.println(conn);

        // Correct INSERT statement syntax
        String query = "INSERT INTO users (student_name, student_id, courses, credit_hours, grades) VALUES (?, ?, ?, ?, ?)";

        try (PreparedStatement stmt = conn.prepareStatement(query)) {
            // Set parameters for the prepared statement
            stmt.setString(1, jstudents);
            stmt.setString(2, jid);
            stmt.setString(3, jcourses);
            stmt.setString(4, jhours);
            stmt.setString(5, jgrades);

            // Use executeUpdate() for INSERT operations
            int rowsAffected = stmt.executeUpdate();

            // Check if insert was successful
            result = (rowsAffected > 0);
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        if (result) {
            JOptionPane.showMessageDialog(this, "Your GPA is ", " ", JOptionPane.INFORMATION_MESSAGE);

            //WelcomeFrame welcome = new WelcomeFrame();
            // welcome.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "You are no more a student", "Error", JOptionPane.INFORMATION_MESSAGE);

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jcalculateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GpaCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GpaCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GpaCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GpaCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GpaCalculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea jId;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JButton jcalculate;
    private javax.swing.JLabel jcourses;
    private javax.swing.JPanel jform;
    private javax.swing.JLabel jgrades;
    private javax.swing.JLabel jhours;
    private javax.swing.JLabel jid;
    private javax.swing.JComboBox<String> jselect;
    private javax.swing.JLabel jstudents;
    private javax.swing.JTextArea tfcourses;
    private javax.swing.JTextArea tfgrades;
    private javax.swing.JTextArea tfhours;
    private javax.swing.JScrollPane tfid;
    private javax.swing.JTextArea tfstudents;
    // End of variables declaration//GEN-END:variables
}
